version: '3.9'

services:
  app:
    image: 'goosfraba-api'
    build:
      context: .
    container_name: goosfraba-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
          condition: service_healthy
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres: